name: '[builder] Docker image for Github repo'

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
  IMAGE_NAME: lyon3timetable

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v3

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            with:
                version: latest

        -   name: Making TAG
            run: |
                TAG=ghcr.io/${{ github.repository }}:latest
                echo "TAG=${TAG,,}" >>${GITHUB_ENV}

        -   name: Build and push
            uses: docker/build-push-action@v5
            with:
                push: true
                tags: ${{ env.TAG }}
                platforms: linux/amd64,linux/arm/v7,linux/arm64
