name: '[builder] Docker image for dockerhub'

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
  IMAGE_NAME: lyon3timetable

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v3
        -
            name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        - 
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            with:
                version: latest
        -
            name: Build dockerfile (with push)
            run: |
                IMAGE_ID=${{ github.repository }}/$IMAGE_NAME:latest
                IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
                docker buildx build \
                --platform=linux/amd64,linux/arm/v7,linux/arm64 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag $IMAGE_ID